// Export every succeeded analysis from the DB to samples/ as JSON (the canonical
// persisted report) + Markdown (human-readable, mirrors the planned report UI).
// Re-run anytime to refresh:
//
//   TURSO_DATABASE_URL=file:local.db pnpm tsx scripts/export-reports.ts
//
// The Markdown rendering doubles as a reference for how the web report page should
// turn report_json into sections + GitHub-linked citations.

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { db } from '../src/db/client';
import type { Report } from '../src/report/schema';

const OUT = 'samples';

function renderMarkdown(repoFull: string, sha: string, report: Report): string {
  const ghLink = (path: string, a: number, b: number) =>
    `https://github.com/${repoFull}/blob/${sha}/${path}#L${a}-L${b}`;
  const out: string[] = [
    `# ${repoFull} — Repo X-Ray report`,
    '',
    `> Commit \`${sha}\` · generated by [repo-xray](https://github.com/zeroindex-ai/repo-xray)`,
    '',
    report.summary,
    '',
  ];
  for (const section of report.sections) {
    out.push(`## ${section.title}`, '');
    for (const f of section.findings) {
      out.push(`- **${f.claim}**${f.severity ? ` _(${f.severity})_` : ''}`);
      out.push(`  ${f.detail}`);
      for (const c of f.evidence) {
        out.push(`  - [\`${c.path}:${c.startLine}-${c.endLine}\`](${ghLink(c.path, c.startLine, c.endLine)})`);
      }
    }
    out.push('');
  }
  return out.join('\n');
}

async function main() {
  mkdirSync(OUT, { recursive: true });
  const analyses = await db().execute(
    "SELECT id, owner, repo, commit_sha FROM analyses WHERE status = 'succeeded' ORDER BY created_at"
  );
  if (analyses.rows.length === 0) {
    console.log('No succeeded analyses to export.');
    return;
  }
  for (const row of analyses.rows) {
    const r = row as Record<string, unknown>;
    const id = String(r.id);
    const owner = String(r.owner);
    const repo = String(r.repo);
    const sha = String(r.commit_sha);
    const rep = await db().execute({
      sql: 'SELECT report_json FROM reports WHERE analysis_id = ?',
      args: [id],
    });
    if (!rep.rows[0]) continue;
    const report = JSON.parse(String((rep.rows[0] as Record<string, unknown>).report_json)) as Report;

    writeFileSync(join(OUT, `${repo}.report.json`), JSON.stringify(report, null, 2) + '\n');
    writeFileSync(join(OUT, `${repo}.report.md`), renderMarkdown(`${owner}/${repo}`, sha, report) + '\n');
    console.log(`✓ ${owner}/${repo} @ ${sha.slice(0, 8)} → ${OUT}/${repo}.report.{json,md}`);
  }
}

void main();
